use_frameworks!

platform :ios, '9.0'

target 'MultithreadingKnowledge_Example' do
  pod 'MultithreadingKnowledge', :path => '../'

  target 'MultithreadingKnowledge_Tests' do
    inherit! :search_paths

    pod 'FBSnapshotTestCase'
  end
end
